### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#154]
As discussed with @jsiarto and Trevor today:

- [x] Move pills for assets to the right  #143
- [x] Add border around metadata tables via wrapper #143
- [x] Catalogs: datetime as pill behind title in list view? #217
- [x] ~catalogs: if icon is present add it over the title in tiles view~ #145
- [x] deprecated: set opcaity
- [x] ~not deprecated, but versions: add pill "multiple versions" and on hover open popup with list of links to next/prev versions~ can't use popover in cards it seems #149
- [x] eye icon is confusing
- [x] proj:shape/bbox/geometry: show in popover as wkt or geojson, also allow copy and opening it in geojson.io. #141
- [x] put filters into a new sidebar or popover? #216
- [x] fullscreen button for tables #215
- [x] in tables show only max length of text per cell, open popover for arrays and objects #215
- [x] ~External icon is missing in provider list / metadata etc~ -> see #168 
- [x] Remove bullets from additional resources links?
