### ISSUE TITLE
Support for STAC 1.1

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#455]
ToDo:
- [x] Update stac-migrate => https://github.com/stac-utils/stac-migrate/issues/9
- [x] Update stac-fields => https://github.com/stac-utils/stac-fields/issues/29
- [ ] Update STAC Browser => #462
